// Code generated by cmd/codegen from https://github.com/saffronjam/cimgui-go.
// DO NOT EDIT.


#pragma once

#include "../cwrappers/cimplot.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif