// Code generated by cmd/codegen from https://github.com/saffronjam/cimgui-go.
// DO NOT EDIT.

#pragma once

#include "wrapper.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
